### ISSUE TITLE
Set up Ethnio screener on the site 

### ISSUE THREAD

**Issue by yowill** [18F/eregs-platform#34]

**Comment by jehlers** [comment]
Here is the js for each of the two screeners. I will have access to turn them on and off and change the targeting from ethn.io's user interface. _(Right now they are both turned off.)_

**Code for the homepage screener:**
`
<script type="text/javascript" language="javascript" src="//ethn.io/95928.js" async="true" charset="utf-8"></script>`

**Code for the success page screener:**
`
<script type="text/javascript" language="javascript" src="//ethn.io/36020.js" async="true" charset="utf-8"></script>`

**Comment by cmc333333** [comment]
Now present, but we should test before closing.

**Comment by yowill** [comment]
Turned on today!

**Comment by jehlers** [comment]
Thanks @cmc333333!
