### ISSUE TITLE
Continue user research 

### ISSUE THREAD

**Issue by yowill** [18F/eregs-platform#47]

**Comment by jehlers** [comment]
We've spoken to 7 external users so far. We have 1 more scheduled for Monday next week, and a few more emails waiting for responses.

We have meetings planned with the 2 internal EPA rule writers next week to discuss the comment output. The contractor who usually sorts the comments is also planning to let us know when he is ready to chat if at all.

I'm happy to close this issue for now and make a new one next sprint to complete user research and synthesize the results. Thoughts @donjo or anything I missed? Can you post the bullets you had in the sprint demo here and then close?

**Comment by donjo** [comment]
I think you got it all. 

### Early observations
- Comment tool mostly well-received
- Some usability concerns around navigating the document
- Some confusion around where to leave a comment (comment heading, section heading, on a paragraph)
- Saving/building a comment could use some work
