### ISSUE TITLE
Right sidebar tweaks

### ISSUE THREAD

**Issue by jehlers** [18F/eregs-platform#53]
cc @cmc333333 
## Right sidebar modules

Generally the right sidebar looks great. The change that seems to have happened is the size of the module. 

**Current ATF:**

<img width="556" alt="screen shot 2016-08-25 at 12 32 54 pm" src="https://cloud.githubusercontent.com/assets/4267825/17977542/281c9b44-6ac0-11e6-8f0c-8e631e047976.png">

**Current EPA/default:**

<img width="1040" alt="screen shot 2016-08-25 at 12 33 16 pm" src="https://cloud.githubusercontent.com/assets/4267825/17977557/332bd036-6ac0-11e6-9859-9a5384b0e6ce.png">

I'm _leaning_ towards keeping the larger size in the EPA/default version because it will be easier for fingers to touch on a screen. However, if we do keep that size, I think we should make sure it matches with the tab headers in the drawer on the left side of the screen. Meaning:

<img width="1280" alt="screen shot 2016-08-25 at 12 36 04 pm" src="https://cloud.githubusercontent.com/assets/4267825/17977674/a1119cac-6ac0-11e6-8df3-a1090c9657e0.png">
- [x] The height of the white area around the TOC text is 42ish px. The area the defines the SxS module is 44ish px. Let's have them match. I think the TOC height is best. 
- [x] The text in these "boxes" should also match. The "TABLE OF CONTENTS" looks much bigger than "SECTION-BY-SECTION ANALYSIS" and "HELP". The right sidebar headers should be bigger and match the size/hierarchy of the TOC.
## Defined terms

I think we have a bug of sorts here. The size of the header and such for this module should match what I mentioned above. But, when I clicked on a definition, I saw this:

<img width="330" alt="screen shot 2016-08-25 at 12 30 49 pm" src="https://cloud.githubusercontent.com/assets/4267825/17977814/26a66460-6ac1-11e6-9ec1-7dcd6c958932.png">

I _think_ they gray is there for while the term is loading? I did see the proper :spinner: animated gif. :) But then the text stayed gray (not accessible). To fix:
- [x] Defined term header should match the font size/hierarchy, box height, and color of the other right sidebar modules. 
- [x] The (X) should be vertically centered in that space. Same as the (+) and (-) icons in the other modules. _(Same goes for the animated spinner if it is off kilter.)
## Help

The current ATF version looks like this:

<img width="324" alt="screen shot 2016-08-25 at 12 46 04 pm" src="https://cloud.githubusercontent.com/assets/4267825/17978003/f91f99d4-6ac1-11e6-874f-e0633b15be24.png">

The new EPA/default version looks like this:

<img width="324" alt="screen shot 2016-08-25 at 12 46 12 pm" src="https://cloud.githubusercontent.com/assets/4267825/17978013/020e2cc2-6ac2-11e6-8989-7acac6de2c76.png">

I'm focusing specifically here on the titles inside this module: "INTERFACE HELP" and "TEXTUAL HELP." They are not meant to be bigger than their headers. Meaning the sizing is more accurate in the ATF version above. Wondering if this means that our H5 style isn't defined? 
- [x] The size of those headers should either match the size of the text inside the module bars ("HELP," "DEFINED TERM," etc...) or be smaller. Also notice that the "(What's this?)" link is smaller. That is the size those headers should be.

**Comment by cmc333333** [comment]
All merged in with https://github.com/eregs/regulations-site/pull/461
