### ISSUE TITLE
Type hierarchy tweaks

### ISSUE THREAD

**Issue by jehlers** [18F/eregs-platform#54]
I'm going to write a novel or maybe more of an ode to typography here, so I apologize in advance. 
## Type hierarchy from a skinable platform standpoint

What I’m seeing in @cmc333333’s two shots of the munitions list is the difference in size between Source Sans Pro and Lato. 

**Current ATF screenshot (Lato):**

<img width="642" alt="screen shot 2016-08-24 at 12 36 51 pm" src="https://cloud.githubusercontent.com/assets/4267825/17978923/3ca8b4a2-6ac6-11e6-8713-cea97e5083c6.png">

**New EPA/default added styles to ATF (Source sans pro sizing):**

<img width="606" alt="screen shot 2016-08-24 at 12 36 59 pm" src="https://cloud.githubusercontent.com/assets/4267825/17978932/48bdac84-6ac6-11e6-8fa4-040df39c2af9.png">

The issue here is not with the hierarchy. The hierarchy is good! But the size of the font at that level in the hierarchy is where the issue lies. :yay fun part! — and by fun I mean hard. 😁:

We have two different fonts in play here. Lato for ATF's brand and Source sans pro for the EPA/default/web design standards brand. 

Lato as a san serif font is very geometric and round. The x-height is higher than that of source sans pro. And, because of the geometric style/shape, the bowls of the letters (space inside a "p" or "d" or "o") is wider.

![xheight](https://cloud.githubusercontent.com/assets/4267825/17979263/b1874206-6ac7-11e6-8722-22daa410679a.gif)

<img width="901" alt="screen shot 2016-08-25 at 1 32 54 pm" src="https://cloud.githubusercontent.com/assets/4267825/17979467/bcf7cbd2-6ac8-11e6-8d11-58e7ab7e8d8c.png">

**This matters because certain fonts are easier to read at smaller sizes than others.** Lato falls under this bucket, and is one of the reasons we chose it for ATF's brand. See ATF's hierarchy:

![lato](https://cloud.githubusercontent.com/assets/4267825/17979684/f395a5be-6ac9-11e6-9185-386646d9e809.png)

See H4, H5, and H6 in that list are 16px and 12px. Whereas in the EPA/default/web design standards hierarchy, source sans pro is defined as such:

![sourcesanspro](https://cloud.githubusercontent.com/assets/4267825/17979731/20bbc622-6aca-11e6-9059-0cc863eefcd4.png)

See H4, H5, and H6 are defined as 19px and 14px. 

This change in size relates to how small each font can get to still be legible, and hold it's level in the hierarchy next to all the other text. 
### What's the point?

The _size_ of the fonts in the hierarchy should be flexible based on the font we are using for each eRegs instance. The _hierarchy_ should be the same, but the size of the font at each level _can/should_ be able to adjust slightly based on the font choices. Assuming we want to allow different agencies to have the option to choose different fonts to match their brand and agency personality. 

I had pictured creating a few different type hierarchies that we could choose from and apply to a particular eRegs instance. Not sure how it is working now, which is why I also understand that this whole issue may not be attainable right away.

**The immediate solution** would be to let ATF keep the font sizes it is using. 

If we _have_ to combine them. We can probably live with the larger sizes that Source san pro's hierarchy is applying to Lato's. But it will look weird, hence the screen shot at the top of this page. And I'm not sure it is the long term solution.

@cmc333333 😁 sorry... does any of this make sense? what do you think?

**Comment by cmc333333** [comment]
After further investigation, we discovered that the ATF type hierarchy _is_ correct, the underlying data is just funky (with the munitions list title being at the same level as its children). The above was resolved via a scaling factor for the table of contents, however
