### ISSUE TITLE
Adding to the ATF about page and footer

### ISSUE THREAD

**Issue by jehlers** [18F/eregs-platform#57]
Part of #51 
### About page updates
- [x] Change intro paragraph copy as per their request.

We're adding some instructions on how to stop comparing versions to the about page. The new bottom section of the about page should look like this:

![atf-about-02](https://cloud.githubusercontent.com/assets/4267825/18361438/c14e6760-75cf-11e6-8de4-d146adcc901c.png)
- [x] Add "and clicking “Show differences.”" to end of number 3. 
- [x] Add "To stop comparing, return to the regulation timeline tab —   (red timeline svg)     — at the top left side of the screen. Click the “Stop Comparing” button under the second of the two revisions being compared." about 60px of visual space under the photo of the text in diff mode.
- [x] At the same level as the above text, add the following image (so it lines up with the image above -- I may need to save it out different, we can play with this if needed):

![6-atf-timeline-03](https://cloud.githubusercontent.com/assets/4267825/18361647/b221ac10-75d0-11e6-9711-c68d0a83057a.png)
#### Footer updates

We also want to add the two following links to the footer that appears on both the about page and the homepage:
- [x] Department of Justice - https://www.justice.gov/ (add the link to the text that already exists in the footer)
- [x] Privacy Policy - https://www.justice.gov/doj/privacy-policy (add below the DOJ link and 12px regular text)
- [x] Legal Policies & Disclaimers - https://www.justice.gov/legalpolicies (add on the same line and same style as above links)

![screen shot 2016-09-08 at 2 34 07 pm](https://cloud.githubusercontent.com/assets/4267825/18361788/4e9cd39e-75d1-11e6-83ca-bfbf91b297f0.png)

**Comment by tadhg-ohiggins** [comment]
@jehlers The image above doesn't quite work—I'm not sure why, but the regtimeline-01.png image is wider in its natural state than it is when displayed on the page. I think this means that the new image needs to match both the full width of https://github.com/18F/atf-eregs/blob/master/atf_eregs/static/regulations/img/regtimeline-01.png and to have the “stop comparing” element match the width of the UI examples in regtimeline-01.png.

**Comment by jehlers** [comment]
@tadhg-ohiggins gotcha. I wasn't sure when I saved it out. I can try to match that now.

**Comment by jehlers** [comment]
How's this:

![6-atf-timeline-03](https://cloud.githubusercontent.com/assets/4267825/18591827/46f1567e-7c02-11e6-8499-38879a0457a0.png)

**Comment by tadhg-ohiggins** [comment]
Addressed in https://github.com/18F/atf-eregs/pull/442 and https://github.com/18F/atf-eregs/pull/443
Note that the definitions of _citation_ and _defined term_ haven't been changed as part of those PRs, and also that minor CSS work will have to be done again after we switch to SCSS. That last part is tracked in https://github.com/18F/atf-eregs/issues/444
(I'm leaving this issue open until the fixes are in production.)
