### ISSUE TITLE
2 Plan what components are configurable

### ISSUE THREAD

**Issue by cmc333333** [18F/eregs-platform#9]
We need a list of all of the custom bits we'll expect agencies to be able to modify. ATF's the prime example here, FEC needs much heavier customization (and hence might not be a good use case), EPA needs a small amount of customization.

We know we need:
- [ ] Colors
- [ ] Fonts
- [ ] Logos

but no doubt need more.

**Comment by donjo** [comment]
Some notes from the discussion @jehlers, @xtine and I had about which parts should be able to be themed.

### Fonts

Right now we define a sans front and a serif font but the true breakdown is probably like "UI font" and "body text font" 

### Logos

Logos in the top right corner (and footer on homepage) should be turned into variables that can be changed.

### Color Functions

These are the different functional elements that can receive unique color treatments.
- text
- header color 
  - header bottom stroke
- sub-header color ***
- table of contents background color ***
- right hand sidebar dropdown color ***
- border color
- link color
- button (primary and secondary) 
- text highlight color (diffs)
- success green
- failure red
- warning orange/light blue

_**\* - it is recommended that these be the same color_

**Comment by donjo** [comment]
Additionally, when a lighter or darker version of a color needs to be used (hover state, active state, etc.) it should be defined independently and not created through the use of SASS functions.
